import type { DigestContent } from "./generator";

export function renderMarkdown(digest: DigestContent): string {
  const lines: string[] = [];

  // Header
  lines.push(`# Weekly Intel Digest`);
  lines.push(`## Week ${digest.weekNumber} | ${digest.dateRange}`);
  lines.push(``);
  lines.push(
    `*${digest.sourceIndex.length} sources | ${digest.themes.length} themes | Generated ${new Date(digest.generatedAt).toLocaleString()}*`
  );
  lines.push(``);

  // Executive Summary
  lines.push(`## Executive Summary`);
  lines.push(``);
  for (const point of digest.executiveSummary) {
    lines.push(`- ${point}`);
  }
  lines.push(``);

  // Themes
  lines.push(`## Key Themes`);
  lines.push(``);

  digest.themes.forEach((theme, idx) => {
    const statusBadge =
      theme.noveltyStatus === "new"
        ? "🆕"
        : theme.noveltyStatus === "follow-up"
          ? "🔄"
          : "📌";
    lines.push(`### ${idx + 1}. ${theme.name} ${statusBadge}`);
    lines.push(``);
    lines.push(theme.summary);
    lines.push(``);

    if (theme.items.length > 1) {
      lines.push(`**Related items:**`);
      for (const item of theme.items) {
        const link = item.url ? `[${item.title}](${item.url})` : item.title;
        lines.push(`- ${link} (${item.source})`);
      }
      lines.push(``);
    }
  });

  // Hot Takes
  if (digest.hotTakes.length > 0) {
    lines.push(`## Hot Takes`);
    lines.push(``);
    lines.push(`| Take | Source | Context |`);
    lines.push(`|------|--------|---------|`);
    for (const take of digest.hotTakes.slice(0, 10)) {
      const escapedTake = take.take.replace(/\|/g, "\\|");
      const escapedContext = take.context.replace(/\|/g, "\\|");
      lines.push(
        `| ${escapedTake} | ${take.author ? `${take.author} via ` : ""}${take.source} | ${escapedContext} |`
      );
    }
    lines.push(``);
  }

  // Signals to Watch
  if (digest.signalsToWatch.length > 0) {
    lines.push(`## Signals to Watch`);
    lines.push(``);
    for (const signal of digest.signalsToWatch) {
      lines.push(`- ${signal}`);
    }
    lines.push(``);
  }

  // Source Index
  lines.push(`## Source Index`);
  lines.push(``);
  lines.push(`| Source | Type | Items |`);
  lines.push(`|--------|------|-------|`);
  for (const source of digest.sourceIndex) {
    lines.push(`| ${source.name} | ${source.type} | ${source.itemCount} |`);
  }
  lines.push(``);

  // Footer
  lines.push(`---`);
  lines.push(`*Generated by Weekly Intel on ${new Date().toLocaleString()}*`);

  return lines.join("\n");
}

export function renderHtml(digest: DigestContent): string {
  const statusColors = {
    new: "#22c55e",
    "follow-up": "#eab308",
    ongoing: "#6b7280",
  };

  const statusLabels = {
    new: "New",
    "follow-up": "Follow-up",
    ongoing: "Ongoing",
  };

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Weekly Intel - ${digest.weekNumber}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
      line-height: 1.6;
      color: #1f2937;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
      background: #f9fafb;
    }
    @media (prefers-color-scheme: dark) {
      body { background: #111827; color: #f9fafb; }
      .card { background: #1f2937; border-color: #374151; }
      .executive-summary { background: #1e3a5f; border-color: #2563eb; }
      .hot-take { background: #3f1f1f; border-color: #dc2626; }
      table { background: #1f2937; }
      th { background: #374151; }
      td { border-color: #374151; }
    }
    .header {
      text-align: center;
      margin-bottom: 30px;
      padding-bottom: 20px;
      border-bottom: 2px solid #e5e7eb;
    }
    .header h1 { margin: 0; font-size: 28px; }
    .header .meta { color: #6b7280; font-size: 14px; margin-top: 8px; }
    .card {
      background: white;
      border: 1px solid #e5e7eb;
      border-radius: 8px;
      padding: 20px;
      margin-bottom: 20px;
    }
    .executive-summary {
      background: #eff6ff;
      border: 1px solid #3b82f6;
      border-left-width: 4px;
    }
    .executive-summary h2 { color: #1d4ed8; margin-top: 0; }
    .executive-summary ul { margin-bottom: 0; }
    .badge {
      display: inline-block;
      padding: 2px 8px;
      border-radius: 4px;
      font-size: 12px;
      font-weight: 600;
      color: white;
      margin-left: 8px;
    }
    .theme-header {
      display: flex;
      align-items: center;
      margin-bottom: 10px;
    }
    .theme-header h3 { margin: 0; }
    .hot-take {
      background: #fef2f2;
      border-left: 4px solid #dc2626;
      padding: 15px;
      margin-bottom: 15px;
      border-radius: 0 8px 8px 0;
    }
    .hot-take .take { font-weight: 600; margin-bottom: 5px; }
    .hot-take .meta { font-size: 13px; color: #6b7280; }
    table {
      width: 100%;
      border-collapse: collapse;
      background: white;
      border-radius: 8px;
      overflow: hidden;
    }
    th, td {
      padding: 12px 15px;
      text-align: left;
      border-bottom: 1px solid #e5e7eb;
    }
    th { background: #f3f4f6; font-weight: 600; }
    .footer {
      text-align: center;
      color: #6b7280;
      font-size: 13px;
      margin-top: 30px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
    }
    a { color: #2563eb; text-decoration: none; }
    a:hover { text-decoration: underline; }
  </style>
</head>
<body>
  <div class="header">
    <h1>Weekly Intel Digest</h1>
    <div class="meta">Week ${digest.weekNumber} | ${digest.dateRange}</div>
    <div class="meta">${digest.sourceIndex.length} sources | ${digest.themes.length} themes</div>
  </div>

  <div class="card executive-summary">
    <h2>Executive Summary</h2>
    <ul>
      ${digest.executiveSummary.map((point) => `<li>${escapeHtml(point)}</li>`).join("")}
    </ul>
  </div>

  <h2>Key Themes</h2>
  ${digest.themes
    .map(
      (theme, idx) => `
    <div class="card">
      <div class="theme-header">
        <h3>${idx + 1}. ${escapeHtml(theme.name)}</h3>
        <span class="badge" style="background: ${statusColors[theme.noveltyStatus]}">${statusLabels[theme.noveltyStatus]}</span>
      </div>
      <p>${escapeHtml(theme.summary)}</p>
      ${
        theme.items.length > 1
          ? `<ul>${theme.items.map((item) => `<li>${item.url ? `<a href="${escapeHtml(item.url)}">${escapeHtml(item.title)}</a>` : escapeHtml(item.title)} (${escapeHtml(item.source)})</li>`).join("")}</ul>`
          : ""
      }
    </div>
  `
    )
    .join("")}

  ${
    digest.hotTakes.length > 0
      ? `
    <h2>Hot Takes</h2>
    ${digest.hotTakes
      .slice(0, 10)
      .map(
        (take) => `
      <div class="hot-take">
        <div class="take">${escapeHtml(take.take)}</div>
        <div class="meta">${take.author ? `${escapeHtml(take.author)} via ` : ""}${escapeHtml(take.source)} — ${escapeHtml(take.context)}</div>
      </div>
    `
      )
      .join("")}
  `
      : ""
  }

  ${
    digest.signalsToWatch.length > 0
      ? `
    <h2>Signals to Watch</h2>
    <div class="card">
      <ul>
        ${digest.signalsToWatch.map((signal) => `<li>${escapeHtml(signal)}</li>`).join("")}
      </ul>
    </div>
  `
      : ""
  }

  <h2>Source Index</h2>
  <table>
    <thead>
      <tr><th>Source</th><th>Type</th><th>Items</th></tr>
    </thead>
    <tbody>
      ${digest.sourceIndex.map((source) => `<tr><td>${escapeHtml(source.name)}</td><td>${escapeHtml(source.type)}</td><td>${source.itemCount}</td></tr>`).join("")}
    </tbody>
  </table>

  <div class="footer">
    Generated by Weekly Intel on ${new Date(digest.generatedAt).toLocaleString()}
  </div>
</body>
</html>`;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export function renderPlainText(digest: DigestContent): string {
  const lines: string[] = [];

  lines.push(`WEEKLY INTEL DIGEST`);
  lines.push(`Week ${digest.weekNumber} | ${digest.dateRange}`);
  lines.push(`${"=".repeat(50)}`);
  lines.push(``);

  lines.push(`EXECUTIVE SUMMARY`);
  lines.push(`${"-".repeat(30)}`);
  for (const point of digest.executiveSummary) {
    lines.push(`• ${point}`);
  }
  lines.push(``);

  lines.push(`KEY THEMES`);
  lines.push(`${"-".repeat(30)}`);
  digest.themes.forEach((theme, idx) => {
    const status =
      theme.noveltyStatus === "new"
        ? "[NEW]"
        : theme.noveltyStatus === "follow-up"
          ? "[FOLLOW-UP]"
          : "[ONGOING]";
    lines.push(`${idx + 1}. ${theme.name} ${status}`);
    lines.push(`   ${theme.summary}`);
    lines.push(``);
  });

  if (digest.hotTakes.length > 0) {
    lines.push(`HOT TAKES`);
    lines.push(`${"-".repeat(30)}`);
    for (const take of digest.hotTakes.slice(0, 10)) {
      lines.push(`• "${take.take}"`);
      lines.push(`  — ${take.author ? `${take.author}, ` : ""}${take.source}`);
      lines.push(``);
    }
  }

  if (digest.signalsToWatch.length > 0) {
    lines.push(`SIGNALS TO WATCH`);
    lines.push(`${"-".repeat(30)}`);
    for (const signal of digest.signalsToWatch) {
      lines.push(`• ${signal}`);
    }
    lines.push(``);
  }

  lines.push(`${"-".repeat(50)}`);
  lines.push(
    `Generated by Weekly Intel on ${new Date(digest.generatedAt).toLocaleString()}`
  );

  return lines.join("\n");
}
